---

# Main tasks file for php-fpm role

- name: Disable default php-fpm service
  service:
    name: php5-fpm
    state: stopped
    enabled: no
  tags: [php-fpm]

- name: Push php.ini
  template:
    src: php.ini.j2
    dest: "{{ item.home~'/etc/php5/fpm/php.ini' }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0644"
  with_items: "{{ php_fpm_pools }}"
  tags: [php-fpm]

- name: Push php-fpm.conf
  template:
    src: php-fpm.conf.j2
    dest: "{{ item.home~'/etc/php5/fpm/php-fpm.conf' }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0644"
  with_items: "{{ php_fpm_pools }}"
  tags: [php-fpm]

- name: Push env.conf
  template:
    src: env.conf.j2
    dest: "{{ item.home~'/etc/php5/fpm/env.conf' }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0644"
  with_items: "{{ php_fpm_pools }}"
  tags: [php-fpm]

- name: Push php-fpm pool
  template:
    src: pool.conf.j2
    dest: "{{ item.home~'/etc/php5/fpm/pool.d/'~item.owner~'.conf' }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0644"
  with_items: "{{ php_fpm_pools }}"
  tags: [php-fpm]

- name: Push php5-fpm-checkconf script
  template:
    src: php5-fpm-checkconf.j2
    dest: "{{ item.home~'/usr/lib/php5/php5-fpm-checkconf' }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0750"
  with_items: "{{ php_fpm_pools }}"
  tags: [php-fpm]

- name: Push php5-fpm-reopenlogs script
  template:
    src: php5-fpm-reopenlogs.j2
    dest: "{{ item.home~'/usr/lib/php5/php5-fpm-reopenlogs' }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0750"
  with_items: "{{ php_fpm_pools }}"
  tags: [php-fpm]

- name: Push sessionclean script
  template:
    src: sessionclean.j2
    dest: "{{ item.home~'/usr/lib/php5/sessionclean' }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0750"
  with_items: "{{ php_fpm_pools }}"
  tags: [php-fpm]

- name: Push sessionclean cron job
  template:
    src: php5.cron.j2
    dest: "{{ '/etc/cron.d/php5-'~item.name }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{ php_fpm_pools }}"
  tags: [php-fpm]

- name: Push php5-fpm logrotate conf
  template:
    src: php5-fpm.logrotate.j2
    dest: "{{ '/etc/logrotate.d/php5-fpm-'~item.name }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{ php_fpm_pools }}"
  tags: [php-fpm]

- name: Create php5-fpm service
  template:
    src: php5-fpm.service.j2
    dest: "{{ '/lib/systemd/system/php5-fpm-'~item.owner~'.service' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{ php_fpm_pools }}"
  tags: [php-fpm]

- name: Enable php5-fpm service
  service:
    name: "{{ 'php5-fpm-'~item.owner }}"
    state: stopped
    enabled: yes
  with_items: "{{ php_fpm_pools }}"
  tags: [php-fpm]

- name: Start php5-fpm service
  service:
    name: "{{ 'php5-fpm-'~item.owner }}"
    state: started
  with_items: "{{ php_fpm_pools }}"
  tags: [php-fpm]
